services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: music_game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal-network
    # Test pour vérifier que Postgres est pleinement opérationnel
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d music_game"]
      interval: 3s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    networks:
      - internal-network

  backend:
    build:
      context: ./backend
    environment:
      PORT: 3001
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres@postgres:5432/music_game
      REDIS_URL: redis://redis:6379
      CORS_ORIGIN: https://devine-beat.lucasspitzer.fr
    depends_on:
      postgres:
        condition: service_healthy # Attend que le healthcheck de Postgres passe au vert
      redis:
        condition: service_started
    networks:
      - internal-network
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.musicgame-backend.rule=Host(`devine-beat.lucasspitzer.fr`) && (PathPrefix(`/api`) || PathPrefix(`/socket.io`))"
      - "traefik.http.routers.musicgame-backend.entrypoints=websecure"
      - "traefik.http.routers.musicgame-backend.tls=true"
      - "traefik.http.routers.musicgame-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.musicgame-backend.loadbalancer.server.port=3001"
    restart: on-failure # Redémarre automatiquement en cas de crash imprévu

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: https://devine-beat.lucasspitzer.fr/api
        VITE_SOCKET_URL: https://devine-beat.lucasspitzer.fr
    depends_on:
      - backend
    networks:
      - internal-network
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.musicgame-frontend.rule=Host(`devine-beat.lucasspitzer.fr`)"
      - "traefik.http.routers.musicgame-frontend.entrypoints=websecure"
      - "traefik.http.routers.musicgame-frontend.tls=true"
      - "traefik.http.routers.musicgame-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.musicgame-frontend.loadbalancer.server.port=80"

volumes:
  postgres_data:

networks:
  internal-network:
    driver: bridge
  traefik-network:
    external: true
    name: proxy